#!/usr/bin/env bash

# This PATH should also be in ~/.zshenv
PATH=/opt/homebrew/bin:/usr/local/bin:/usr/bin:/usr/sbin:/bin:/sbin:/usr/local/sbin

export GPG_TTY=$(tty)
export GREP_OPTIONS='--color=auto'



# END

# DockFlow CLI alias
alias dockflow="/Applications/DockFlow.app/Contents/MacOS/DockFlowCLI"
